- type: entity
  name: кока
  parent: FoodProduceBase
  id: FoodCoca
  description: Листья коки были составной частью в приготовлении колы до кофеина.
  components:
  - type: FlavorProfile
    flavors:
      - leafy
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 7
        - ReagentId: CocaExtract
          Quantity: 4
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/coca.rsi
  - type: Produce
    seedId: coca

- type: entity
  name: ядовитые ягоды
  parent: FoodProduceBase
  id: FoodPoisonBerries
  description: Один из видов множеств ядовитых ягод.
  components:
  - type: FlavorProfile
    flavors:
      - berry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Cyanide
          Quantity: 2
        - ReagentId: Tirizene
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/poisonberries.rsi
  - type: Produce
    seedId: poisonberries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBerry
        Quantity: 8
      - ReagentId: Cyanide
        Quantity: 2
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: ледяной кристалл
  parent: FoodProduceBase
  id: FoodIcecrystal
  description: Ледяной кристалл из холодных далёких земель.
  components:
  - type: FlavorProfile
    flavors:
      - cold
      - oily
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: ColdFrostOil
          Quantity: 11
        - ReagentId: Nutriment
          Quantity: 4
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/icesprout.rsi
  - type: Produce
    seedId: icesprout

- type: entity
  name: лавовый кристалл
  parent: FoodProduceBase
  id: FoodLavacrystal
  description: Лавовый кристалл из горячих далёких земель.
  components:
  - type: FlavorProfile
    flavors:
      - oily
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: HotCapsaicinOil
          Quantity: 11
        - ReagentId: Nutriment
          Quantity: 4
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/lavasprout.rsi
  - type: Produce
    seedId: lavasprout

- type: entity
  name: полипень
  parent: FoodProduceBase
  id: FoodPolypnium
  description: Странный сгусток чёрной слизи прямиком из лавовых земель.
  components:
  - type: FlavorProfile
    flavors:
      - slime
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 17
        reagents:
        - ReagentId: Slime
          Quantity: 10
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: EntropicPolypnium
          Quantity: 3
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/polypnium.rsi
  - type: Produce
    seedId: polypnium

- type: entity
  name: амброзия гайа
  parent: FoodProduceBase
  id: FoodAmbrosiaGaia
  description: Лекарственное растение в котором течёт кровь богов.
  components:
  - type: FlavorProfile
    flavors:
      - leafy
      - medicine
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 16
        reagents:
        - ReagentId: Nutriment
          Quantity: 6
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: Earthsblood
          Quantity: 5
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/ambrosia_gaia.rsi
  - type: Produce
    seedId: ambrosiaGaia
  - type: Extractable
    grindableSolutionName: food
  - type: Clothing
    sprite: Radium/Objects/Specific/Hydroponics/ambrosia_gaia.rsi
    slots:
    - HEAD
  - type: Tag
    tags:
    - Ambrosia

- type: entity
  name: святой арбуз
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodHolymelon
  description: Святой арбуз прямиком из ботаники или из церкви.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
      - watermelon
      - holy
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 34
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
        - ReagentId: Holywater
          Quantity: 20
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/holymelon.rsi
  - type: Produce
    seedId: watermelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Holywater
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodHolymelonSlice
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: ClothingHeadHatHolymelon
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: ломтик святого арбуза
  parent: ProduceSliceBase
  id: FoodHolymelonSlice
  description: Божественно.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - watermelon
      - holy
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/holymelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: Holywater
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Holywater
        Quantity: 4
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: огурец
  parent: FoodProduceBase
  id: FoodCucumber
  description: Огурец даёт силы и воду.
  components:
  - type: FlavorProfile
    flavors:
      - cucumber
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 21
        reagents:
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: Nutriment
          Quantity: 6
        - ReagentId: Water
          Quantity: 10
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/cucumber.rsi
  - type: Produce
    seedId: cucumber
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: CucumberJuice
        Quantity: 10

- type: entity
  name: взрывной лимон
  parent: FoodProduceBase
  id: FoodBombLemon
  description: Взрывной лимон настолько прекрасен, что аж имеет бомбезный вкус.
  components:
  - type: FlavorProfile
    flavors:
      - gunpowder
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: BlackPowder
          Quantity: 4
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.Trigger.TriggerVisuals.VisualState:
        base:
          Primed: { state: primed }
          Unprimed: { state: complete }
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/bomblemon.rsi
    state: produce
    layers:
    - state: produce
      map: ["base"]
  - type: Explosive
    explosionType: DemolitionCharge
    totalIntensity: 15
    intensitySlope: 2
    maxIntensity: 25
    canCreateVacuum: false
  - type: ExplodeOnTrigger
  - type: OnUseTimerTrigger
    delay: 3
    initialBeepDelay: 0
    beepSound: /Audio/Machines/Nuke/general_beep.ogg
  - type: Produce
    seedId: bomblemon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceLemon
        Quantity: 6
      - ReagentId: BlackPowder
        Quantity: 4

- type: entity
  name: мунлин
  parent: FoodProduceBase
  id: FoodMoonlin
  description: Лунный свет!
  components:
  - type: FlavorProfile
    flavors:
      - moonlin
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 13
        reagents:
        - ReagentId: Vitamin
          Quantity: 3
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Moonlin
          Quantity: 5
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/producemoonlin.rsi
  - type: Produce
    seedId: moonlin
  - type: PointLight
    color: "#64d2cb"
    energy: 0.6
    radius: 4
    softness: 1
    offset: "0, -0.5"

- type: entity
  name: 3D апельсин
  parent: FoodLemon
  id: Food3DOrange
  description: Вкусный, а самое главное в 3D!
  components:
  - type: FlavorProfile
    flavors:
      - orange
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: Radium/Objects/Specific/Hydroponics/3Dorange_produce.rsi
  - type: Icon
    sprite: Radium/Objects/Specific/Hydroponics/3Dorange_produce.rsi
    state: icon
  - type: Produce
    seedId: 3Dorange
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceOrange
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
