- type: startingGear
  id: PodClownGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    mask: ClothingMaskClown

- type: startingGear
  id: PodMimeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMime
    head: ClothingHeadHatBeret
    belt: ClothingBeltSuspenders
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    mask: ClothingMaskMime
  innerClothingSkirt: ClothingUniformJumpskirtMime
